# Generated by Django 3.0.8 on 2020-12-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='phonemodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='')),
                ('image2', models.ImageField(upload_to='')),
                ('image3', models.ImageField(upload_to='')),
                ('image4', models.ImageField(upload_to='')),
                ('image5', models.ImageField(upload_to='')),
                ('company', models.CharField(max_length=50)),
                ('mobile_name', models.CharField(max_length=300)),
                ('color', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('RAM', models.CharField(max_length=10)),
                ('storage', models.CharField(max_length=10)),
                ('exp_storage', models.CharField(max_length=10)),
                ('processor', models.CharField(max_length=50)),
                ('front_camera', models.CharField(max_length=50)),
                ('back_camera', models.CharField(max_length=50)),
                ('dimension', models.CharField(max_length=50)),
                ('weight', models.CharField(max_length=50)),
                ('os', models.CharField(max_length=50)),
                ('display_size', models.CharField(max_length=50)),
                ('resolution', models.CharField(max_length=50)),
                ('network_type', models.CharField(max_length=50)),
                ('battery', models.CharField(max_length=50)),
                ('warranty', models.CharField(max_length=50)),
            ],
        ),
    ]
